
[client]
	#Internal
	#Allowed Values: OPEN_EQUIPMENT_MENU, NONE
	tutorialStep = "OPEN_EQUIPMENT_MENU"
	crosshair = "craftingdead:standard"
	displayBlood = true
	#Allowed Values: OFF, KILL, HIT_AND_KILL
	hitMarkerMode = "HIT_AND_KILL"
	killSoundEnabled = true
	killSound = "minecraft:item.trident.return"

