"Enable Base" = true
"Enable Creeper" = true
"Enable Skeleton" = true
"Enable Zombie" = true

[Base]
	#Mobs will run away from exploding creepers / TNT
	"Enable Avoid Explosions" = true
	#Change how mobs target players
	"Enable Targeting" = true

	#Change how mobs target players
	[Base.Targeting]
		#Chance for a mob to be able to see players through blocks.
		#Range: 0.0 ~ 1.0
		"XRay Chance" = 0.2
		#Mobs will no longer take random time to target a player.
		"Instant Target" = true
		#How far away can the mobs see the player. This overrides the vanilla value (16 for most mobs). Setting to 0 will leave the follow range as vanilla.
		#Range: 0 ~ 128
		"Follow Range Override" = 64

[Creeper]
	#Various changes to Creepers exploding. Ignoring Walls, Walking Fuse and smarter exploding based off explosion size
	"Enable Creeper Swell" = true

	#Various changes to Creepers exploding. Ignoring Walls, Walking Fuse and smarter exploding based off explosion size
	[Creeper."Creeper Swell"]
		#Percentage chance for a Creeper to not stand still while exploding.
		#Range: 0.0 ~ 1.0
		"Walking Fuse Chance" = 0.1
		#Breaching creepers will try to open an hole in the wall to let mobs in.
		#Range: 0.0 ~ 1.0
		"Breach Chance" = 0.05
		#If true creepers will ignite if damaged by an explosion.
		"TNT Like" = false
		#AND HIS NAME IS ...
		#Range: 0.0 ~ 1.0
		"Cena Chance" = 0.01
		#Percentage chance for a Creeper to ignore walls while targeting a player. This means that a creeper will be able to explode if it's in the correct range from a player even if there's a wall between.
		#Range: 0.0 ~ 1.0
		"Ignore Walls Chance" = 0.1
		#Launching creepers will try ignite and throw themselves at the player.
		#Range: 0.0 ~ 1.0
		"Launch Chance" = 0.05

[Skeleton]
	#Skeletons are more precise when shooting and strafing is removed, can hit a target from 64 blocks and try to stay away from the target.
	"Enable Skeleton Shoot" = true

	#Skeletons are more precise when shooting and strafing is removed, can hit a target from 64 blocks and try to stay away from the target.
	[Skeleton."Skeleton Shoot"]
		#How much inaccuracy does the arrow fired by skeletons have. Vanilla skeletons have 10/6/2 inaccuracy in easy/normal/hard difficulty.
		#Range: 0.0 ~ 30.0
		"Arrow Inaccuracy" = 0.0
		#Chance for a Skeleton to spawn with the ability to avoid the player
		#Range: 0.0 ~ 1.0
		"Avoid Player chance" = 1.0

[Zombie]
	"Enable Zombie AI" = true

	#No comment
	[Zombie."Zombie AI"]
		#Chance for a Zombie to spawn with the digger ability
		#Range: 0.0 ~ 1.0
		"Digger Chance" = 0.05

