
["Hostile Villages settings"]
	#Percentage of how likely normal,non-zombie villages are to spawn. default: 0
	#Range: 0 ~ 100
	vanillaVillageChance = 0
	#Set higher to increase the generated population of the hostile village, default: 5
	#Range: 1 ~ 100
	hostilePopulationSize = 10
	#Whether to generate extra loot for the village, default: true
	generateLoot = true
	#Turn on debug messages for spawning, default: false
	debugLog = false
	#Disables entities beeing unable to despawn after they get an item equipped, default: true
	disableNoEntityDespawnWhenPickingItem = true
	#List of loottables to use, default: minecraft:chests/simple_dungeon
	loottables = ["minecraft:chests/simple_dungeon"]
	#Whether to allow vanilla villagers to spawn at all. If enabled then hostile villages will get a villager spawn egg added to their loot. default: false
	allowVanillaVillagerSpawn = false
	#List of entity pairs which spawn in villages. Format = entity1;entity2;5;6   5 is the chance of entity2(one in five), 6 is the total weight of this whole entry to be chosen
	villageEntityTypes = ["minecraft:zombie;minecraft:husk;3;14", "minecraft.zombie_villager;minecraft:wither_skeleton;3;8", "minecraft:vindicator;minecraft:illusioner;5;3", "minecraft:pillager;minecraft:evoker;7;7"]
	#Additional structures to add as houses for spawning zombie villages, default: []. Example for bountiful and waystones support: ["bountiful:village/common/bounty_gazebo", "waystones:village/common/waystone"]
	additionalStructures = []
	#Set higher to increase the amount of additional structures generated, note those replace houses, default: 2
	#Range: 1 ~ 100
	additionalStructuresWeight = 2

